#!/bin/sh

set -e
[ -n "$BASH" ] && set -o pipefail
set -u

# defaults
pause=10

usage() {
	cat << EOF
Usage: kreboot [option ...] [kernel]
Options are:
	--wait, -w N	wait N seconds before reboot (default $pause)
	--nowait	don't wait, reboot immediately
EOF
	exit $1
}

uerr() {
	echo "ERROR: $*" 2>&1
	echo
	usage 1
}

# Check that all programs we need are available, exit if not
# (relying on 'set -e' and hash returning non-zero for errors)
hash grubby kexec systemctl

# Process options and arguments
target=''
while test $# -gt 0; do
	case $1 in
		-w|--wait)
			if [ "$#" -lt 2 ]; then
				uerr "Option $1 requires an argument"
			fi
			wait=$2
			if ! printf "%f" $wait > /dev/null 2>&1; then
				uerr "Option $1 argument not a number"
			fi
			shift
			;;
		--nowait)
			wait=0
			;;
		-*)
			uerr "Unrecognized option: $1"
			;;
		*)
			if [ -n "$target" ]; then
				uerr "Extra arguments: $*"
			fi
			target=$1
			;;
	esac
	shift
done

if [ -z "$target" ]; then
	if ! target=$(grubby --default-kernel); then
		# grubby prints error to stdout
		echo "grubby: $target" 1>&2
		exit 1
	fi
fi

if ! info=$(grubby --info=$target); then
	# grubby prints error to stdout
	echo "grubby: $info" 1>&2
	exit 1
fi
eval $(echo "$info" | sed "s|^\(\S*\)=\([^'\"].*\)$|\1='\2'|")

echo Booting $title...
if [ "$pause" -ne 0 ]; then
	echo Press Ctrl-C within $pause seconds to cancel
	sleep $pause
fi

kexec -l "$kernel" --initrd="$initrd" --command-line="root=$root $args"
systemctl kexec
