#!/bin/sh

set -e
[ -n "$BASH" ] && set -o pipefail

# Check that all programs we need are available, exit if not
# (relying on 'set -e' and hash returning non-zero for errors)
hash grubby kexec systemctl

target=$1
[ -z "$target" ] &&
	target=`grubby --default-kernel`
IFS='
'
for l in `grubby --info=$target`; do
	eval `echo $l | sed "s|^\(\S*\)=\([^'\"].*\)$|\1='\2'|"`
done
echo Boot "$title"?
read
kexec -l "$kernel" --initrd="$initrd" --command-line="root=$root $args"
systemctl kexec
